"""D4-equivariant stencil network for learning smoother parameters.

The dihedral group D4 (symmetries of the square) has 8 elements: 4 rotations
and 4 reflections.  A 3x3 stencil transforms under D4 by permuting its
entries.  This module implements group convolution layers over D4 so that
the network's predictions respect these symmetries.

For smoother parameters: the spectral radius / smoothing factor is a D4-
invariant quantity (rotating the problem doesn't change convergence), while
individual RK coefficients may be D4-equivariant or invariant depending on
the smoother structure.
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np


# ---------------------------------------------------------------------------
# D4 group actions on a 3x3 grid
# ---------------------------------------------------------------------------

def _rot90_indices():
    """Index permutation for 90-degree counterclockwise rotation of a 3x3 grid
    stored in row-major order (9 entries)."""
    # (i,j) -> (j, 2-i)
    perm = []
    for i in range(3):
        for j in range(3):
            ni, nj = j, 2 - i
            perm.append(ni * 3 + nj)
    return perm


def _reflect_h_indices():
    """Index permutation for horizontal reflection (flip left-right)."""
    perm = []
    for i in range(3):
        for j in range(3):
            perm.append(i * 3 + (2 - j))
    return perm


def _compose_perm(p1, p2):
    """Compose two permutations: result[i] = p1[p2[i]]."""
    return [p1[p2[i]] for i in range(len(p1))]


def _build_d4_permutations():
    """Build all 8 D4 permutations on a flattened 3x3 grid.

    Returns a list of 8 permutation lists, each of length 9.
    The group is generated by r (90-degree rotation) and s (horizontal flip).
    Elements: {e, r, r^2, r^3, s, sr, sr^2, sr^3}.
    """
    identity = list(range(9))
    r = _rot90_indices()
    s = _reflect_h_indices()

    r2 = _compose_perm(r, r)
    r3 = _compose_perm(r2, r)
    sr = _compose_perm(s, r)
    sr2 = _compose_perm(s, r2)
    sr3 = _compose_perm(s, r3)

    return [identity, r, r2, r3, s, sr, sr2, sr3]


D4_PERMS = _build_d4_permutations()


class D4GroupConv(nn.Module):
    """Group convolution layer over D4.

    Maps a signal on D4 (or a scalar signal lifted to D4) to a new signal
    on D4.  Input shape: (batch, C_in, |D4|, 9) for group features, or
    (batch, C_in, 9) for the lifting layer.

    The weight kernel has shape (C_out, C_in, 9) and is shared across
    group elements via the D4 action on the 3x3 stencil indices.
    """

    def __init__(self, c_in, c_out, is_lifting=False):
        super().__init__()
        self.c_in = c_in
        self.c_out = c_out
        self.is_lifting = is_lifting
        self.weight = nn.Parameter(torch.randn(c_out, c_in, 9) * 0.1)
        self.bias = nn.Parameter(torch.zeros(c_out))

        # Precompute permutation index tensors
        perms = torch.tensor(D4_PERMS, dtype=torch.long)  # (8, 9)
        self.register_buffer("perms", perms)

    def forward(self, x):
        """
        Parameters
        ----------
        x : torch.Tensor
            If lifting (is_lifting=True): shape (B, C_in, 9)
            Else: shape (B, C_in, 8, 9) — signal on D4 x stencil
        """
        G = 8  # |D4|

        if self.is_lifting:
            # x: (B, C_in, 9) -> apply each group element to get (B, C_in, 8, 9)
            # Then convolve with weight
            B = x.shape[0]
            # Permute stencil by each group element
            x_g = x[:, :, self.perms]  # (B, C_in, 8, 9)
            # Inner product with weight kernel
            # weight: (C_out, C_in, 9)
            out = torch.einsum("bcgs,ocs->bog", x_g, self.weight)
            # out: (B, C_out, 8)
            return out + self.bias[None, :, None]
        else:
            # x: (B, C_in, 8, 9) — features over group and stencil
            B = x.shape[0]
            out = torch.zeros(B, self.c_out, G, device=x.device, dtype=x.dtype)
            for g_idx in range(G):
                # Rotate the stencil indices by g
                x_rot = x[:, :, :, self.perms[g_idx]]  # (B, C_in, 8, 9)
                # Sum over input channels and stencil, for each group element
                out[:, :, g_idx] = torch.einsum("bchs,ocs->bo", x_rot, self.weight)
            return out + self.bias[None, :, None]


class D4Invariant(nn.Module):
    """Pool over D4 group dimension to produce an invariant output."""

    def __init__(self, mode="mean"):
        super().__init__()
        self.mode = mode

    def forward(self, x):
        """x: (B, C, 8) -> (B, C) by averaging over the group."""
        if self.mode == "max":
            return x.max(dim=-1).values
        return x.mean(dim=-1)


class D4StencilNet(nn.Module):
    """D4-equivariant network mapping a 3x3 stencil to RK smoother parameters.

    Architecture:
        1. Lifting layer: (B, 1, 9) -> (B, C1, 8) via D4 group convolution
        2. Hidden group conv: (B, C1, 8) -> (B, C2, 8)
        3. D4-invariant pooling: (B, C2, 8) -> (B, C2)
        4. MLP head: (B, C2) -> (B, s-1 + 1) = (alphas, beta)

    The output (smoother parameters) is D4-invariant because the optimal
    smoothing factor does not depend on the orientation of the stencil.
    """

    def __init__(self, n_stages=3, hidden_channels=16):
        """
        Parameters
        ----------
        n_stages : int
            Number of RK stages.  The network outputs (n_stages - 1) alpha
            values and 1 beta value.
        hidden_channels : int
            Width of hidden group-conv layers.
        """
        super().__init__()
        self.n_stages = n_stages
        c1, c2 = hidden_channels, hidden_channels

        self.lift = D4GroupConv(1, c1, is_lifting=True)
        self.gconv1 = D4GroupConv(c1, c2, is_lifting=False)
        self.pool = D4Invariant(mode="mean")
        self.head = nn.Sequential(
            nn.Linear(c2, 32),
            nn.ReLU(),
            nn.Linear(32, n_stages),  # s-1 alphas + 1 beta
        )

    def forward(self, stencil):
        """
        Parameters
        ----------
        stencil : torch.Tensor of shape (B, 3, 3) or (B, 9)
            The operator stencil at each sample point.

        Returns
        -------
        alphas : torch.Tensor of shape (B, n_stages - 1)
        beta : torch.Tensor of shape (B,)
        """
        B = stencil.shape[0]
        x = stencil.reshape(B, 1, 9)  # (B, 1, 9)

        x = torch.relu(self.lift(x))         # (B, c1, 8)
        # For gconv1 we need (B, C_in, 8, 9) — broadcast stencil to group
        # Use the lifted features directly (they're already on the group)
        # We skip the second group conv over stencil and just use the pooled
        # group features, since the stencil is the same at each group element
        x = self.pool(x)                     # (B, c1)
        out = self.head(x)                   # (B, n_stages)

        alphas = torch.sigmoid(out[:, :-1])  # alphas in (0, 1)
        beta = F.softplus(out[:, -1])    # beta > 0
        return alphas, beta

    def predict_from_stencil(self, stencil_3x3):
        """Convenience method for a single 3x3 stencil (no batch dim)."""
        x = torch.tensor(stencil_3x3, dtype=torch.float32).unsqueeze(0)
        alphas, beta = self(x)
        return alphas.squeeze(0), beta.squeeze(0)


def demo_equivariance():
    """Verify that the network output is invariant under D4 rotations."""
    net = D4StencilNet(n_stages=3, hidden_channels=16)
    net.eval()

    # A non-symmetric stencil (advection-diffusion)
    stencil = torch.tensor([
        [0.0, -0.3, 0.0],
        [-0.8, 3.0, -0.5],
        [0.0, -0.4, 0.0],
    ], dtype=torch.float32)

    # Apply all D4 transformations and check invariance
    results = []
    flat = stencil.reshape(9)
    for perm in D4_PERMS:
        rotated = flat[torch.tensor(perm)].reshape(1, 3, 3)
        with torch.no_grad():
            alphas, beta = net(rotated)
        results.append((alphas.numpy(), beta.item()))

    alpha_vals = np.array([r[0] for r in results])
    beta_vals = np.array([r[1] for r in results])
    alpha_spread = alpha_vals.std(axis=0).max()
    beta_spread = beta_vals.std()

    print("D4 equivariance check:")
    print(f"  Alpha spread across D4 transforms: {alpha_spread:.6f}")
    print(f"  Beta spread across D4 transforms:  {beta_spread:.6f}")
    print(f"  (Values near 0 confirm equivariance)")
    return alpha_spread, beta_spread


if __name__ == "__main__":
    demo_equivariance()
